name: Download Weather Data

on:
  schedule:
    - cron: "0 10 * * *" 
  workflow_dispatch:  

jobs:
  fetch-weather-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Athenry Weather Data
      run: |
        mkdir -p data/weather
        wget -O data/weather/weather.json https://prodapi.metweb.ie/observations/athenry/today

    - name: Commit and Push Changes
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/weather/weather.json
          git commit -m "Update weather data"
          git push