name: Download Weather Data

on:
  schedule:
    - cron: "0 10 * * *" 
  workflow_dispatch:  

jobs:
  fetch-weather-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Athenry Weather Data
      run: |
        mkdir -p data/weather
        wget -O data/weather/weather.json https://prodapi.metweb.ie/observations/athenry/today
